import { defineField, defineType } from "sanity";

export const dogTypes = defineType({
	name: "dog",
	title: "Nos chiens",
	type: "document",

	fieldsets: [
		{
			name: "general",
			title: "Informations générales",
			options: { collapsible: true, collapsed: false },
		},
		{
			name: "health",
			title: "Santé",
			options: { collapsible: true, collapsed: false },
		},
		{
			name: "needs",
			title: "Besoins",
			options: { collapsible: true, collapsed: true },
		},
		{
			name: "affinities",
			title: "Affinités",
			options: { collapsible: true, collapsed: true },
		},
		{
			name: "care",
			title: "Entretien",
			options: { collapsible: true, collapsed: true },
		},
	],

	fields: [
		defineField({
			name: "name",
			title: "Nom du chien",
			type: "string",
			validation: (rule) => rule.required(),
			fieldset: "general",
		}),
		defineField({
			name: "slug",
			title: "Identifiant (slug)",
			type: "slug",
			options: { source: "name", maxLength: 96 },
			validation: (rule) => rule.required(),
			fieldset: "general",
		}),
		defineField({
			name: "dogprority",
			title: "Chien prioritaire",
			type: "array",
			of: [{ type: "string" }],
			options: {
				list: [{ title: "oui", value: "dogprority" }],
			},
			validation: (rule) => rule.required().min(1),
			fieldset: "general",
		}),
		defineField({
			name: "arrivalDate",
			title: "Arrivée au refuge",
			type: "datetime",
			initialValue: () => new Date().toISOString(),
			validation: (rule) => rule.required(),
			fieldset: "general",
		}),
		defineField({
			name: "mainImage",
			title: "Image principale du chien",
			type: "image",
			options: { hotspot: true },
		}),
		defineField({
			name: "gallery",
			title: "Liste d'images",
			type: "array",
			of: [{ type: "image", options: { hotspot: true } }],
		}),
		defineField({
			name: "age",
			title: "Âge",
			type: "number",
			validation: (rule) => rule.required(),
			fieldset: "general",
		}),
		defineField({
			name: "weight",
			title: "Poids",
			type: "number",
			validation: (rule) => rule.required(),
			fieldset: "general",
		}),
		defineField({
			name: "gender",
			title: "Sexe",
			type: "string",
			options: {
				list: [
					{ title: "Mâle", value: "male" },
					{ title: "Femelle", value: "female" },
				],
			},
			validation: (rule) => rule.required(),
			fieldset: "general",
		}),
		defineField({
			name: "historyDescription",
			title: "Histoire du chien",
			type: "array",
			of: [{ type: "block" }],
			fieldset: "general",
		}),
		defineField({
			name: "shortDescription",
			title: "Courte description du chien",
			type: "string",
			fieldset: "general",
		}),
		defineField({
			name: "breed",
			title: "Race du chien",
			type: "string",
			options: {
				list: [
					{ title: "Berger Allemand", value: "german_shepherd" },
					{ title: "Labrador Retriever", value: "labrador_retriever" },
					{ title: "Golden Retriever", value: "golden_retriever" },
					{ title: "Bouledogue Français", value: "french_bulldog" },
					{ title: "Beagle", value: "beagle" },
					{ title: "Caniche", value: "poodle" },
					{ title: "Rottweiler", value: "rottweiler" },
					{ title: "Yorkshire Terrier", value: "yorkshire_terrier" },
					{ title: "Boxer", value: "boxer" },
					{ title: "Siberian Husky", value: "siberian_husky" },
					{ title: "Dachshund", value: "dachshund" },
					{ title: "Doberman", value: "doberman" },
					{ title: "Shih Tzu", value: "shih_tzu" },
					{ title: "Chihuahua", value: "chihuahua" },
					{ title: "Cocker Spaniel", value: "cocker_spaniel" },
					{ title: "Bichon Frisé", value: "bichon_frise" },
					{ title: "Border Collie", value: "border_collie" },
					{ title: "Mastiff", value: "mastiff" },
					{ title: "Saint-Bernard", value: "saint_bernard" },
					{ title: "Akita Inu", value: "akita_inu" },
				],
			},
			validation: (rule) => rule.required(),
			fieldset: "general",
		}),

		defineField({
			name: "healthStatus",
			title: "Statut sanitaire",
			type: "array",
			of: [{ type: "string" }],
			options: {
				list: [
					{ title: "Vacciné", value: "vaccinated" },
					{ title: "Non vacciné", value: "not_vaccinated" },
					{ title: "Vermifugé", value: "dewormed" },
					{ title: "Stérilisé", value: "sterilized" },
				],
			},
			validation: (rule) => rule.required().min(1),
			fieldset: "health",
		}),
		defineField({
			name: "healthDescription",
			title: "Description sanitaire",
			type: "array",
			of: [{ type: "block" }],
			fieldset: "health",
		}),

		defineField({
			name: "needs",
			title: "Le chien a besoin de",
			type: "array",
			of: [{ type: "string" }],
			options: {
				list: [
					{ title: "Appartement possible", value: "apartment_friendly" },
					{ title: "Maison", value: "house_required" },
					{ title: "Maison avec jardin", value: "garden_required" },
					{ title: "Foyer calme", value: "calm_environment" },
					{ title: "Routine stable", value: "stable_routine" },
					{ title: "Présence humaine régulière", value: "human_presence" },
					{
						title: "Peut rester seul quelques heures",
						value: "can_be_left_alone",
					},
					{ title: "Sans jeune enfant", value: "no_young_children" },
				],
			},
			validation: (rule) => rule.required().min(1),
			fieldset: "needs",
		}),
		defineField({
			name: "needsDescription",
			title: "Besoin du chien",
			type: "array",
			of: [{ type: "block" }],
			fieldset: "needs",
		}),

		defineField({
			name: "affinities",
			title: "Affinités du chien",
			type: "array",
			of: [{ type: "string" }],
			options: {
				list: [
					{ title: "Chiens femelles", value: "female_dogs" },
					{ title: "Chiens mâles", value: "male_dogs" },
					{ title: "Tous les chiens", value: "all_dogs" },
					{ title: "Chat à éviter", value: "avoid_cats" },
					{ title: "Enfants à éviter", value: "avoid_children" },
					{ title: "Enfants calmes", value: "calm_children" },
				],
			},
			validation: (rule) => rule.required().min(1),
			fieldset: "affinities",
		}),
		defineField({
			name: "affinitiesDescription",
			title: "Mes affinités",
			type: "array",
			of: [{ type: "block" }],
			fieldset: "affinities",
		}),

		defineField({
			name: "care",
			title: "Entretien & rythme",
			type: "array",
			of: [{ type: "string" }],
			options: {
				list: [
					{ title: "Poils courts", value: "short_hair" },
					{ title: "Poils mi-longs", value: "medium_hair" },
					{ title: "Brossage régulier", value: "regular_brushing" },
					{ title: "Besoin d’activités", value: "active_dog" },
					{ title: "Pas de course", value: "no_running" },
					{ title: "Balade tranquille", value: "calm_walks" },
				],
			},
			validation: (rule) => rule.required().min(1),
			fieldset: "care",
		}),
		defineField({
			name: "healthCare",
			title: "Description pour l'entretien & rythme",
			type: "array",
			of: [{ type: "block" }],
			fieldset: "care",
		}),
	],
});
